name: build

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'Cargo.toml'
      - 'src/**/*'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'Cargo.toml'
      - 'src/**/*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.config.platform }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - platform: ubuntu-22.04
            target: 'x86_64-unknown-linux-gnu'

          - platform: macos-latest
            target: 'x86_64-apple-darwin'

          - platform: macos-latest
            target: 'aarch64-apple-darwin'

          - platform: windows-latest
            target: 'x86_64-pc-windows-msvc'
    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.config.target }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Install Dependencies
        if: matrix.config.platform == 'ubuntu-22.04'
        run: sudo apt-get install -y build-essential libssl-dev pkg-config cmake libgtk-3-dev libclang-dev libglib2.0-dev libx11-dev

      - name: Add targets
        run: rustup target add ${{ matrix.config.target }}

      - name: Define GIT_HASH
        id: sha
        run: echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build
        run: cargo build --release --target ${{ matrix.config.target }}
        env:
          GIT_HASH: ${{ steps.sha.outputs.GIT_HASH }}
          RUSTFLAGS: -Awarnings

      - name: Upload binary
        if: matrix.config.platform != 'windows-latest'
        uses: actions/upload-artifact@v7
        with:
          name: orbolay-${{ matrix.config.target }}
          path: target/${{ matrix.config.target }}/release/orbolay

      - name: Upload binary (Windows)
        if: matrix.config.platform == 'windows-latest'
        uses: actions/upload-artifact@v7
        with:
          name: orbolay-${{ matrix.config.target }}
          path: target/${{ matrix.config.target }}/release/orbolay.exe

  bundle:
    needs: build
    runs-on: ${{ matrix.config.platform }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - platform: ubuntu-22.04
            target: 'x86_64-unknown-linux-gnu'
            bundles: ['appimage', 'deb']

          - platform: macos-latest
            target: 'x86_64-apple-darwin'
            bundles: ['osx']

          - platform: macos-latest
            target: 'aarch64-apple-darwin'
            bundles: ['osx']
    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.config.target }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Add targets
        run: rustup target add ${{ matrix.config.target }}

      - name: Add bundler
        run: cargo install cargo-bundle --locked

      - name: Download binary
        uses: actions/download-artifact@v7
        with:
          name: orbolay-${{ matrix.config.target }}
          path: target/${{ matrix.config.target }}/release/

      - name: Bundle
        run: cargo bundle --release --target ${{ matrix.config.target }}
        env:
          CARGO_BUNDLE_SKIP_BUILD: 1
          GIT_HASH: ${{ steps.sha.outputs.GIT_HASH }}
          RUSTFLAGS: -Awarnings

      - name: (macOS) Zip app
        if: matrix.config.platform == 'macos-latest'
        run: |
            cd target/${{ matrix.config.target }}/release/bundle/osx/
            zip -r Lamina-${{ matrix.config.target }}.app.zip Lamina.app

      - name: Upload AppImage
        if: matrix.config.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v7
        with:
          name: orbolay-${{ matrix.config.target }}.AppImage
          path: target/${{ matrix.config.target }}/release/bundle/appimage/orbolay*.AppImage

      - name: Upload deb
        if: matrix.config.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v7
        with:
          name: orbolay-${{ matrix.config.target }}.deb
          path: target/${{ matrix.config.target }}/release/bundle/deb/orbolay*.deb

      - name: Upload macOS app
        if: matrix.config.platform == 'macos-latest'
        uses: actions/upload-artifact@v7
        with:
          name: orbolay-${{ matrix.config.target }}.app
          path: target/${{ matrix.config.target }}/release/bundle/osx/Lamina-${{ matrix.config.target }}.app.zip
